### ISSUE TITLE
overflow使用时的问题

### ISSUE THREAD

**Issue by xpinus** [guhuaijin/react-code-diff#7]
更改过多想要给盒子添加overflow: scroll的效果时发现，如果仅仅添加overflow那么左侧的数字框不会隐藏，需要添加position：relative属性，据我观察是因为行号的元素使用了absolute
```html
<div className={styles.diffWraper}>
                <CodeDiff  />
</div>
```
```less
.diffWraper {
  max-height: 400px;
  overflow-y: auto;
  position: relative;   // 必须有，否则出问题
}
```
